import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ArrowUpIcon } from "lucide-react";
import Providers from "./Providers";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Oprik software - PAGINAS WEB Y APLICACIONES PARA TELEFONOS EN ARGENTINA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh] body-gradient max-w-[1580px] mx-auto bg-[#131316] px-2 md:px-0`}
      >
        <Providers>
          <Navbar />
          <div className="max-w-[1480px] mx-auto px-2 md:px-12">
            {children}
          </div>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
